main:
  hosts:
    aqua:
      ansible_host: aqua.aquatan.studio
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./id_rsa
share:
  hosts:
    newt:
      ansible_host: newt.aquatan.studio
      ansible_ssh_user: deploy
      ansible_ssh_private_key_file: ./id_rsa
