galaxy_info:
  author: pddg
  role_name: octopass
  description: ansible role to install octopass linux user management with github organization/team.
  license: CC0
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
        - trusty
        - precise
  galaxy_tags:
    - system
    - users
    - security
  dependencies: []
