---

- name: install apt-transport-https for prerequisite
  apt:
    name: apt-transport-https
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: import linyows/octopass key
  apt_key:
    id: 871257A0BC9106C4
    url: https://packagecloud.io/linyows/octopass/gpgkey
    state: present

- name: configure octopass apt repository
  template:
    src: linyows_octopass.list
    dest: /etc/apt/sources.list.d/linyows_octopass.list
  register: octopass_apt_list

- name: Update cache
  apt:
    update_cache: yes
  when: octopass_apt_list.changed

- name: install octopass
  apt:
    name: octopass
    state: present

- name: configure octopass
  template:
    src: octopass.conf
    dest: /etc/octopass.conf
    owner: root
    mode: 0644

- name: try octopass could get passwd
  command: '/usr/bin/octopass passwd'
  register: octopass_passwd
  changed_when: False
  failed_when: octopass_passwd.stdout == ''

- name: configure sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    line: '{{ item }}'
    validate: '/usr/sbin/sshd -t -f %s'
  with_items:
    - 'AuthorizedKeysCommandUser root'
    - 'AuthorizedKeysCommand /usr/bin/octopass'
    - 'UsePAM yes'
    - 'PasswordAuthentication no'
  notify:
    - restart sshd

- name: configure nss switch
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: yes
  with_items:
    - {regexp: '^passwd:\s+(.*?)($|\soctopass$)', line: 'passwd:     \1 octopass'}
    - {regexp: '^shadow:\s+(.*?)($|\soctopass$)', line: 'shadow:     \1 octopass'}
    - {regexp: '^group: \s+(.*?)($|\soctopass$)', line: 'group:      \1 octopass'}

- name: configure pam sshd
  lineinfile:
    path: /etc/pam.d/sshd
    line: '{{ item.line }}'
    state: '{{ item.state }}'
  with_items:
    - {line: '@include common-auth', state: 'absent'}
    - {line: 'auth requisite pam_exec.so quiet expose_authtok /usr/bin/octopass pam', state: 'present'}
    - {line: 'auth optional pam_unix.so not_set_pass use_first_pass nodelay', state: 'present'}
    - {line: 'session required pam_mkhomedir.so skel: /etc/skel/ umask: 0022', state: 'present'}
